{
 "title": "Teku - Single",
 "description": "Dashboard to monitor a single Teku instance",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "system", "label": "System", "query": { "query": "beacon_slot" } },
   { "name": "validator_job", "query": "${VAR_VALIDATOR_JOB}" }
  ]
 },
 "panels": [
  {
   "title": "BEACON CHAIN",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Current slot",
   "type": "stat",
   "description": "Current slot according to system time",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_slot{}" }
   ]
  },
  {
   "title": "Head slot",
   "type": "stat",
   "description": "Current slot according to system time",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_slot{instance=\"$system\"}"
    }
   ]
  },
  {
   "title": "Justified Epoch",
   "type": "stat",
   "description": "Current finalized epoch",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_current_justified_epoch{instance=\"$system\"}"
    }
   ]
  },
  {
   "title": "Finalized Epoch",
   "type": "stat",
   "description": "Current finalized epoch",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_finalized_epoch{instance=\"$system\"}"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_peer_count{instance=\"$system\"}"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "description": "The current epoch according to system time",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_epoch{instance=\"$system\"}"
    }
   ]
  },
  {
   "title": "Slots Behind",
   "type": "stat",
   "description": "Number of slots the head block is behind.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_slot{instance=\"$system\"} - beacon_head_slot{instance=\"$system\"}"
    }
   ]
  },
  {
   "title": "Justification Delay (epochs)",
   "type": "stat",
   "description": "Number of epochs that justification has been delayed.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(beacon_epoch{instance=\"$system\"} - beacon_current_justified_epoch{instance=\"$system\"} - 1, 0)"
    }
   ]
  },
  {
   "title": "Finalisation Delay (epochs)",
   "type": "stat",
   "description": "Number of epochs that finalisation has been delayed.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(beacon_epoch{instance=\"$system\"} - beacon_finalized_epoch{instance=\"$system\"} - 2, 0)"
    }
   ]
  },
  {
   "title": "Correct Attestation Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_previous_correct_validators{instance=\"$system\"} / beacon_previous_active_validators{instance=\"$system\"}"
    }
   ]
  },
  {
   "title": "Trailing Distance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "beacon_slot{instance=\"$system\"} - beacon_head_slot{instance=\"$system\"}",
     "legendFormat": "Head Slot"
    },
    {
     "expr": "clamp_min(beacon_epoch{instance=\"$system\"} - beacon_current_justified_epoch{instance=\"$system\"} - 1, 0)",
     "legendFormat": "Justification Delay"
    },
    {
     "expr": "clamp_min(beacon_epoch{instance=\"$system\"} - beacon_finalized_epoch{instance=\"$system\"} - 2, 0)",
     "legendFormat": "Finalisation Delay"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "graph",
   "description": "Number of slots between when an attestation is created to when it is included in a block. The minimum possible inclusion distance is 1.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "beacon_previous_live_validators{instance=\"$system\"} / beacon_previous_active_validators{instance=~\"$system\"}",
     "legendFormat": "Live Validators"
    },
    {
     "expr": "beacon_previous_correct_validators{instance=\"$system\"} / beacon_previous_active_validators{instance=~\"$system\"}",
     "legendFormat": "Correct Validators"
    }
   ]
  },
  {
   "title": "Gossip Messages",
   "type": "graph",
   "description": "Rate of gossip messages received per second.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(libp2p_gossip_messages_total{instance=~\"$system\"}[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "SYSTEM",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Percentage of attestations in each epoch with the correct head root, correct target root and that were successfully included in blocks.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=~\"$system\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=\"$system\"}",
     "legendFormat": "{{job}} {{pool}} Used"
    },
    {
     "expr": "sum by (instance) (jvm_memory_pool_bytes_used{instance=\"$system\"})",
     "legendFormat": "{{job}} {{pool}} Used Total"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"$system\"}",
     "legendFormat": "{{job}} {{pool}} Process Total"
    },
    {
     "expr": " (jvm_memory_pool_bytes_max{instance=\"$system\"})",
     "legendFormat": "{{job}} {{pool}} Max"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$system\"}",
     "legendFormat": "System Memory"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=\"$system\"}[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}