# config file version
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://localhost:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://127.1.1.0:3100
    editable: true
    version: 1
