# config file version
apiVersion: 1

# List of contact points to import or update
contactPoints:
  # <int> organization ID, default = 1
  - orgId: 1
    # <string, required> name of the contact point
    name: tg
    receivers:
      # <string, required> unique identifier for the receiver
      - uid: Telegram_uid
        # <string, required> type of the receiver
        type: telegram
        settings:
        # <string, required>
          bottoken: "5613838485:AAFCtuLn01J8U4oqmqlieB1AlFOCFWJ-te0"
        # <string, required>
          chatid: "-636105578"
        # <string>
          message: |
            {{ template "default.message" . }}


